version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      PG_HOST: localhost
      NODE_ENV: development
      DIALECT: postgres
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: grocerydelivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
